### ISSUE TITLE
Cập nhật TKB

### ISSUE THREAD

**Issue by MarkusKhoa** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#10]
[tkb_courses_07-08-2020_hk_1_nh2020_vpdb.xlsx](https://github.com/loia5tqd001/Dang-Ky-Hoc-Phan-UIT/files/5062361/tkb_courses_07-08-2020_hk_1_nh2020_vpdb.xlsx)
Do OEP đăng thời khoá biểu trễ hơn nên có cập nhật lại mã lớp CS114.L11.KHCL vào ngày thứ 6 tiết 678.

**Comment by loia5tqd001** [comment]
Cho mình hỏi file excel bạn lấy từ đâu vậy.
Bạn có thể inbox mình cho tiện nha https://www.messenger.com/t/loia5tqd001

**Comment by loia5tqd001** [comment]
À, bạn có thể tự upload database excel được nha bạn.
![image](https://user-images.githubusercontent.com/31364664/90017194-56c33580-dcd5-11ea-990a-c3f44965b97a.png)
