### ISSUE TITLE
Load file 900 row lag quá ?

### ISSUE THREAD

**Issue by hotrungnhan** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#25]
page 2 load 900 dòng file của trường lag quá anh ơi,  
em đọc cái https://ag-grid.com/javascript-data-grid/row-models/ thấy implement theo 3 kiểu còn lại thì k cần load hết 900 row lên dom , như vậy sẽ đỡ lag hơn nhiều ó. Tradeoff là không có Quick Filter nên sẽ filter chậm hơn , mà chắc không sao đâu , a xem thử xem.

[tkb_khdt_16-12-2021_1639622627_hk_2_nh2021.xlsx](https://github.com/loia5tqd001/Dang-Ky-Hoc-Phan-UIT/files/7755985/tkb_khdt_16-12-2021_1639622627_hk_2_nh2021.xlsx)

**Comment by hotrungnhan** [comment]
tách branch của v1 với v2 nữa anh, hiện cái github page vẫn v1 á ...

**Comment by loia5tqd001** [comment]
Cái Github page vẫn v1, còn v2 anh deploy lên Vercel, là để giữ cả 2v như e nói á 😁

**Comment by hotrungnhan** [comment]
> Cái Github page vẫn v1, còn v2 anh deploy lên Vercel, là để giữ cả 2v như e nói á 😁

à em cứ tưởng a deploy bị lỗi mà k để ý  =))

**Comment by loia5tqd001** [comment]
Chắc em cũng ra trường rồi :v. Anyway anh mới update phiên bản mới nhất khá xịn xò rồi đó

**Comment by hotrungnhan** [comment]
à e cũng mới ra năm nay =))

**Comment by hotrungnhan** [comment]
thanks a anyway :<
