### ISSUE TITLE
LỖI HIỂN THỊ!!!!!

### ISSUE THREAD

**Issue by CSboob** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#3]
Sao dữ liệu nó ko hiển thị trong table v bạn ơi?
![Screenshot from 2020-08-04 15-12-41](https://user-images.githubusercontent.com/61237821/89270243-466fe280-d665-11ea-902f-71008f31aa63.png)

**Comment by loia5tqd001** [comment]
Có một số môn là **thực hành hình thức 2**, là không có lịch học cố định á bạn. 
Anh Văn thì mỗi tuần học 2 buổi.
Môn lý thuyết bình thường thì mỗi tuần học 1 buổi.
Môn thực hành HT1 thì 2 tuần học 1 buổi.
Còn thực hành HT2 thì 1 kỳ học 3 buổi.
