### ISSUE TITLE
một môn có 2 lịch

### ISSUE THREAD

**Issue by 18520769** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#4]
Môn giải tích lớp MA006.L12 trong tkb có 2 lớp với 2 giờ học khác nhau là ca 9,10 vào thứ 3 và ca 6,7,8 vào thứ 5. Lúc xếp lịch thì em bị nói là trùng lịch của ca vào t3 vs môn khác nhưng tại bên cái tkb của trang hỗ trợ tạo thời khóa biểu để ca là 6,7,8 vào thứ 5.
Làm ơn xin hỗ trợ.

**Comment by loia5tqd001** [comment]
Mới fix lại. Bạn xem đúng chưa nhé.
https://github.com/loia5tqd001/Dang-Ky-Hoc-Phan-UIT/commit/b6e4da71399fb64839a663eeeb33bd2262abe656
