### ISSUE TITLE
Chưa cập nhật môn Toán cho khoa học máy tính

### ISSUE THREAD

**Issue by taolaobd** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#6]
Dạ do thời khoá biểu mới update nên chưa thể tạo trong bản sao và thời khoá biểu ạ

**Comment by loia5tqd001** [comment]
Bạn inbox mình nói rõ hơn giúp nha https://www.messenger.com/t/loia5tqd001

**Comment by taolaobd** [comment]
Kiểm tra tin nhắn chờ ạ
