### ISSUE TITLE
Cập nhật csdl

### ISSUE THREAD

**Issue by BigBanana9331** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#7]
Chưa cập nhật môn Máy học CS114
Trên dkhp.uit.edu.vn đã có môn này

**Comment by loia5tqd001** [comment]
Bạn inbox mình dùm nha: https://www.messenger.com/t/loia5tqd001
Btw, mình đang dự định làm lại để không cần cập nhật dữ liệu mà ứng dụng vẫn chạy tốt được, chắc kì sau mới có, hẹn bạn kì sau có ứng dụng tốt hơn nha ^^
