### ISSUE TITLE
Lỗi không cho phép 2 môn HT1 trùng

### ISSUE THREAD

**Issue by huyng12** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#8]
## Expect
Hai môn **HT1** là `IT005.L11.CNCL.1` và `IT004.L11.CNCL.1` phải đều được nằm cùng nhau vì 2 môn này có thể học xen kẽ tuần.

## Actual
```
Trùng thời khóa biểu: IT005.L11.CNCL.1:Thứ3Tiết12345 - IT004.L11.CNCL.1:Thứ3Tiết12345. Nếu bạn thấy lỗi là do chương trình vui lòng báo lỗi tại đây
```

Mong bạn cập nhật bản vá lỗi này~

**Comment by loia5tqd001** [comment]
À, cái này theo quy định là **không có được học xen kẽ tuần nha**. Vì đôi khi có một số môn, nửa học kỳ đầu lớp .1 học trước lớp .2, nửa học kỳ sau lớp .2 học trước lớp .1, nên chưa chắc thực tế sẽ được xen kẽ, nên **không cho phép đăng ký học xen kẽ nha**.

Nếu bạn còn thắc mắc có thể inbox mình cho tiện hơn nha: https://www.messenger.com/t/loia5tqd001
Với nếu thấy hay thì đừng quên thả star giúp mình nhé :v
