### ISSUE TITLE
Lỗi sai lich môn học Môn CS419.L11 (Lịch học Thứ 6 nhưng lại sắp xếp Thứ 5)

### ISSUE THREAD

**Issue by githubbinh** [loia5tqd001/Dang-Ky-Hoc-Phan-UIT#9]

**Comment by loia5tqd001** [comment]
Cái này là do **theo file excel của trường thì môn đó là thứ 5 -123**. Tuy nhiên mình thấy **trong trang dkhp thì là thứ 6-678 giống như bạn nói thật**, nên mình [vừa hotfix](https://github.com/loia5tqd001/Dang-Ky-Hoc-Phan-UIT/commit/62c95fd05843895ce908a71f8a07d4484004b5bf) thay đổi dataset cho lớp đó thành 6-678 rồi *(với trang vẽ tkb chứ không update file google sheets)*, bạn check lại xem dùm nha.

Dự tính là học kỳ sau mình sẽ làm thành một ứng dụng web hoàn chỉnh và tốt hơn, để những môn edge case như này các bạn muốn hotfix mình vẫn sẽ có cách cho các bạn tự thay đổi dataset dễ dàng luôn. Cảm ơn bạn đã góp ý nha.
![image](https://user-images.githubusercontent.com/31364664/89981782-b6521e80-dc9e-11ea-93b6-09c30ef3a7fa.png)
